"""Build Kaggle notebooks from code/*.py and push / run / fetch them with the Kaggle CLI.

The scripts in code/ stay the single source of truth. A built notebook:
  1. records git commit + library versions,
  2. writes every helper module (code/*.py not starting with a digit) and the
     selected numbered scripts into /kaggle/working/code via %%writefile,
  3. runs each selected script with %run (an exception fails the notebook),
  4. leaves outputs in /kaggle/working/results (downloadable with `fetch`).

Usage (from the repo root):
  python tools/kaggle_nb.py build 01                # build only -> build/kaggle/<slug>/
  python tools/kaggle_nb.py push 01                 # build + push (runs on Kaggle)
  python tools/kaggle_nb.py push 02 03 04 --gpu     # several scripts, one kernel, GPU on
  python tools/kaggle_nb.py push --all --gpu --wait # whole pipeline, wait, download results
  python tools/kaggle_nb.py status 01
  python tools/kaggle_nb.py fetch 01 --sync         # download outputs, copy results/ into repo
  python tools/kaggle_nb.py push 02 04 05 --include results/best_params.json   # reuse tuned params
  python tools/kaggle_nb.py push --all --env N_TRIALS=80 N_SEEDS=5             # change budgets

Each kernel is a fresh machine: if a script needs files produced by an earlier
script (e.g. 03 needs 02's processed data), include the earlier script too.
"""
import argparse
import datetime as dt
import json
import os
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
CODE_DIR = REPO_ROOT / "code"
BUILD_DIR = REPO_ROOT / "build" / "kaggle"
OUTPUT_DIR = REPO_ROOT / "build" / "kaggle_outputs"
CONFIG_FILE = Path(__file__).with_name("kaggle_config.json")

KAGGLE_WORKDIR = "/kaggle/working"
REPORT_PACKAGES = ["numpy", "pandas", "scikit-learn", "xgboost", "lightgbm",
                   "catboost", "shap", "optuna", "matplotlib", "imbalanced-learn"]


# --------------------------------------------------------------------------- config

def load_config():
    with open(CONFIG_FILE, encoding="utf-8") as f:
        cfg = json.load(f)
    if not cfg.get("username"):
        cfg["username"] = os.environ.get("KAGGLE_USERNAME") or _username_from_kaggle_json()
    return cfg


def _username_from_kaggle_json():
    path = Path(os.environ.get("KAGGLE_CONFIG_DIR", Path.home() / ".kaggle")) / "kaggle.json"
    with open(path, encoding="utf-8") as f:
        return json.load(f)["username"]


# --------------------------------------------------------------------------- scripts

def numbered_scripts():
    return sorted(p for p in CODE_DIR.glob("*.py") if p.name[0].isdigit())


def helper_modules():
    return sorted(p for p in CODE_DIR.glob("*.py") if not p.name[0].isdigit())


def resolve_scripts(names, use_all):
    available = numbered_scripts()
    if use_all:
        return available
    if not names:
        sys.exit("error: give script names (e.g. 01 or 01_eda) or --all")
    chosen = []
    for name in names:
        stem = Path(name).stem
        hits = [p for p in available if p.stem == stem or p.stem.split("_")[0] == stem]
        if len(hits) != 1:
            sys.exit(f"error: '{name}' matches {[p.name for p in hits]} in {CODE_DIR}")
        chosen.append(hits[0])
    return sorted(set(chosen))


def default_slug(cfg, scripts, use_all):
    suffix = "full" if use_all else "-".join(p.stem.replace("_", "-") for p in scripts)
    return f"{cfg['slug_prefix']}-{suffix}"[:50].strip("-")


# --------------------------------------------------------------------------- notebook

def _cell(cell_type, source):
    import hashlib
    cell_id = hashlib.sha1(f"{cell_type}:{source}".encode()).hexdigest()[:12]
    cell = {"id": cell_id, "cell_type": cell_type, "metadata": {},
            "source": source.splitlines(keepends=True)}
    if cell_type == "code":
        cell.update(execution_count=None, outputs=[])
    return cell


def _git_info():
    def run(*args):
        try:
            return subprocess.run(["git", *args], cwd=REPO_ROOT, capture_output=True,
                                  text=True, check=True).stdout.strip()
        except (subprocess.CalledProcessError, FileNotFoundError):
            return ""
    commit = run("rev-parse", "--short", "HEAD") or "unknown"
    dirty = bool(run("status", "--porcelain", "--", "code"))
    return commit + ("-dirty" if dirty else "")


def build_notebook(scripts, cfg, args):
    commit = _git_info()
    env_overrides = dict(kv.split("=", 1) for kv in (args.env or []))
    built = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    names = ", ".join(p.name for p in scripts)
    cells = [_cell("markdown",
                   f"# {cfg['project_title']}\n\n"
                   f"Auto-generated by `tools/kaggle_nb.py` from the GitHub repo. Do not edit here.\n\n"
                   f"- scripts: {names}\n- git commit: `{commit}`\n- built: {built}\n")]

    if args.pip:
        cells.append(_cell("code", "!pip install -q " + " ".join(args.pip)))

    cells.append(_cell("code", f"""import json, os, sys, platform
from importlib.metadata import version, PackageNotFoundError
os.chdir("{KAGGLE_WORKDIR}")
os.makedirs("code", exist_ok=True)
os.makedirs("results", exist_ok=True)
sys.path.insert(0, os.path.abspath("code"))
overrides = {json.dumps(env_overrides)}
os.environ.update(overrides)
env = {{"cpu_count": os.cpu_count(), "platform": platform.platform(), "python": platform.python_version(), "git_commit": "{commit}", "scripts": {json.dumps([p.name for p in scripts])}, "env_overrides": overrides}}
for pkg in {json.dumps(REPORT_PACKAGES)}:
    try:
        env[pkg] = version(pkg)
    except PackageNotFoundError:
        env[pkg] = None
try:
    import subprocess
    env["gpu"] = subprocess.run(["nvidia-smi", "--query-gpu=name", "--format=csv,noheader"],
                                capture_output=True, text=True).stdout.strip() or None
except FileNotFoundError:
    env["gpu"] = None
with open("results/env_kaggle.json", "w") as f:
    json.dump(env, f, indent=2)
print(json.dumps(env, indent=2))
"""))

    for path in helper_modules() + list(scripts):
        src = path.read_text(encoding="utf-8")
        cells.append(_cell("code", f"%%writefile code/{path.name}\n{src}"))

    for rel in args.include or []:
        path = (REPO_ROOT / rel).resolve()
        rel_posix = path.relative_to(REPO_ROOT).as_posix()
        folder = os.path.dirname(rel_posix) or "."
        cells.append(_cell("code", f"os.makedirs({folder!r}, exist_ok=True)"))
        cells.append(_cell("code", f"%%writefile {rel_posix}\n{path.read_text(encoding='utf-8')}"))

    for path in scripts:
        cells.append(_cell("markdown", f"## Run `{path.name}`"))
        cells.append(_cell("code", f"%run code/{path.name}"))

    cells.append(_cell("code", "!ls -la results"))

    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def build(args, cfg):
    scripts = resolve_scripts(args.scripts, args.all)
    slug = args.slug or default_slug(cfg, scripts, args.all)
    if not re.fullmatch(r"[a-z0-9][a-z0-9-]{4,49}", slug):
        sys.exit(f"error: slug '{slug}' must be 5-50 chars of a-z, 0-9, '-'")
    out = BUILD_DIR / slug
    out.mkdir(parents=True, exist_ok=True)

    nb = build_notebook(scripts, cfg, args)
    with open(out / "notebook.ipynb", "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=1)

    meta = {
        "id": f"{cfg['username']}/{slug}",
        "title": slug,
        "code_file": "notebook.ipynb",
        "language": "python",
        "kernel_type": "notebook",
        "is_private": not args.public,
        "enable_gpu": args.gpu,
        "enable_tpu": False,
        "enable_internet": args.internet or bool(args.pip),
        "dataset_sources": [cfg["dataset"]],
        "competition_sources": [],
        "kernel_sources": [],
    }
    with open(out / "kernel-metadata.json", "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2)

    print(f"built {out / 'notebook.ipynb'}")
    print(f"  kernel: {meta['id']}  gpu={meta['enable_gpu']}  internet={meta['enable_internet']}"
          f"  private={meta['is_private']}")
    print(f"  scripts: {', '.join(p.name for p in scripts)}")
    return out, meta["id"], slug


# --------------------------------------------------------------------------- kaggle cli

def kaggle(*args, capture=False):
    exe = shutil.which("kaggle")
    if not exe:
        sys.exit("error: kaggle CLI not found (pip install kaggle)")
    res = subprocess.run([exe, *args], text=True, capture_output=capture)
    if res.returncode != 0:
        if capture:
            sys.stderr.write(res.stdout + res.stderr)
        sys.exit(f"error: kaggle {' '.join(args)} failed ({res.returncode})")
    return res.stdout if capture else ""


def kernel_id_for(args, cfg):
    if args.slug:
        return f"{cfg['username']}/{args.slug}", args.slug
    scripts = resolve_scripts(args.scripts, args.all)
    slug = default_slug(cfg, scripts, args.all)
    return f"{cfg['username']}/{slug}", slug


def status(kernel_id):
    out = kaggle("kernels", "status", kernel_id, capture=True).strip()
    print(out)
    m = re.search(r'status "?([A-Za-z.]+)"?', out)
    return (m.group(1).split(".")[-1].lower() if m else "unknown"), out


def fetch(kernel_id, slug, sync):
    dest = OUTPUT_DIR / slug
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)
    kaggle("kernels", "output", kernel_id, "-p", str(dest), "--force")
    print(f"downloaded outputs to {dest}")
    if sync:
        src = dest / "results"
        if not src.is_dir():
            sys.exit(f"error: no results/ folder in {dest}")
        target = REPO_ROOT / "results"
        target.mkdir(exist_ok=True)
        n = 0
        for f in src.rglob("*"):
            if f.is_file():
                rel = f.relative_to(src)
                (target / rel).parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(f, target / rel)
                n += 1
        print(f"synced {n} files into {target}")


def wait(kernel_id, poll, max_failures=10):
    failures = 0
    while True:
        try:
            state, _ = status(kernel_id)
            failures = 0
        except SystemExit:  # transient network/API error: retry
            failures += 1
            if failures >= max_failures:
                raise
            time.sleep(poll)
            continue
        if state in ("complete", "error", "cancelacknowledged", "cancelrequested"):
            return state
        time.sleep(poll)


# --------------------------------------------------------------------------- main

def main():
    sys.stdout.reconfigure(line_buffering=True)
    cfg = load_config()
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    def common(sp):
        sp.add_argument("scripts", nargs="*", help="numbered scripts, e.g. 01 or 02_preprocess")
        sp.add_argument("--all", action="store_true", help="all numbered scripts in order")
        sp.add_argument("--slug", help="kernel slug (default: derived from script names)")

    for name in ("build", "push"):
        sp = sub.add_parser(name)
        common(sp)
        sp.add_argument("--gpu", action="store_true", help="enable GPU accelerator")
        sp.add_argument("--internet", action="store_true", help="enable internet")
        sp.add_argument("--pip", nargs="+", metavar="PKG", help="pip install before running (turns on internet)")
        sp.add_argument("--public", action="store_true", help="make the kernel public (default private)")
        sp.add_argument("--include", nargs="+", metavar="FILE",
                        help="repo text files to recreate on Kaggle, e.g. results/best_params.json")
        sp.add_argument("--env", nargs="+", metavar="KEY=VALUE",
                        help="environment variables for the run, e.g. N_TRIALS=60 N_SEEDS=5")
        if name == "push":
            sp.add_argument("--wait", action="store_true", help="poll until finished, then fetch --sync")
            sp.add_argument("--poll", type=int, default=30, help="seconds between status checks")

    sp = sub.add_parser("status")
    common(sp)
    sp = sub.add_parser("fetch")
    common(sp)
    sp.add_argument("--sync", action="store_true", help="copy downloaded results/ into repo results/")

    args = p.parse_args()

    if args.cmd == "build":
        build(args, cfg)
    elif args.cmd == "push":
        out, kernel_id, slug = build(args, cfg)
        kaggle("kernels", "push", "-p", str(out))
        print(f"pushed: https://www.kaggle.com/code/{kernel_id}")
        if args.wait:
            state = wait(kernel_id, args.poll)
            fetch(kernel_id, slug, sync=(state == "complete"))
            if state != "complete":
                sys.exit(f"kernel finished with status '{state}'; log saved in {OUTPUT_DIR / slug}")
    elif args.cmd == "status":
        status(kernel_id_for(args, cfg)[0])
    elif args.cmd == "fetch":
        fetch(*kernel_id_for(args, cfg), sync=args.sync)


if __name__ == "__main__":
    main()
